### ISSUE TITLE
Starting one task from another causes the first task to never finish

### ISSUE THREAD

**Issue by theRobinator** [orchestrator/orchestrator#62] opened 2015-02-04 19:25 UTC
Using gulp 3.8.10 (which comes with orchestrator 0.3.7)
```javascript
gulp.task('test', function() {
    var deferred = q.defer();
    gulp.start('subtest', function() {
        console.log('this is a callback');
        deferred.resolve();
    });
    console.log('running the main target');
    return deferred.promise;
});

gulp.task('subtest', function() {
    var deferred = q.defer();
    console.log('In the subtest');
    setTimeout(function() { deferred.resolve(); }, 10);
    return deferred.promise;
});
```

Running the "test" task now outputs:
```
[11:06:04] Starting 'test'...
[11:06:04] Starting 'subtest'...
In the subtest
running the main target
[11:06:04] Finished 'subtest' after 12 ms
```

The callback in the test function is never called, and the program exits before the "test" task finishes.

I realize that this contrived example is easily doable using task dependencies, but my actual code is trying to run a long list of tasks with at most 4 ever executing at once. For that, I need this functionality.

**Comment by robrich** [comment] 2015-02-05 22:32
Duplicate of https://github.com/orchestrator/orchestrator/issues/15, and one of the main focuses of gulp 4.

**Closed by robrich** 2015-02-05 22:32 UTC
